export const ANSWER_QUESTION = 'ANSWER_QUESTION';

export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const REMOVE_EXPERIENCE = 'REMOVE_EXPERIENCE';
export const UPDATE_EXPERIENCE = 'UPDATE_EXPERIENCE';